import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from "@mui/material";

import { createTheme } from '@mui/material/styles';

export const metadata = {
  title: "VitalPath",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

      <ClerkProvider>
        <html lang="en">
          <head>
            <link rel="icon" type="image/x-icon" href="favicon.ico"></link>
             <link
              href="https://fonts.googleapis.com/css2?family=Righteous&family=Roboto&display=swap" 
              rel="stylesheet">

             </link>
          </head>
          <body>
            {children}
          </body>
        </html>
      </ClerkProvider>

  );
}
